ams.py

Implement listing resources (topics/subscriptions)
Implement fetching resource info (topics/subscription)
Implement topic publish
Add routes for subscription pull, ack

Add list/get topics and subscriptions. Add publish to topic

---

argo-ams-library.spec
setup.py

Added gitignored spec file

---

MANIFEST.in
argo-ams-library.spec
examples/consume-pull.py
examples/publisher.py
pymod/__init__.py
pymod/ams.py
pymod/amsexceptions.py

/please review @themiszamani @kaggis

ARGO-710 Provide examples of simple publishing and consuming

---

README.md

Updated Readme File 

---

pymod/ams.py

List subscriptions: Update the response of list subscriptions. Return the whole json

List subscriptions: Update the response of list subscriptions.

---

tests/test_client.py

- Add request url assertions
- Fix assertions in some tests
- Complete subscription pull and acknowledge tests
- Lint code

Fix unit tests issues. Complete sub pull related unit test. Lint

---

pymod/ams.py

- Reformat docstrings 
- Removed unused **reqkwargs

Reformat docstrings. Remove unused arguments

---

pymod/ams.py

Reverts ARGOeu/argo-ams-library#20

Revert "Reformat docstrings. Remove unused arguments"

---

examples/publish.py
pymod/amsmsg.py
tests/test_client.py

ARGO-770 AMS Library tests

---

pymod/ams.py

and in ArgoMessagingService::has_sub

ARGO-804 Has topic/sub methods should have ability to pass kwargs to python-requests library

---

documentation/conf.py

add baseurl to help github render the css

[ARGO-829] - Sphinx documentation to ams library

---

pymod/ams.py
pymod/amsexceptions.py
pymod/amssubscription.py
tests/amsmocks.py
tests/test_client.py
tests/test_subscription.py

This one introduces higher-level call/method `AmsSubscription.offsets(offset='all', moveto=0)` that combines the logic of two underlying methods `getoffsets_sub()` and `modifyoffset_sub()`.

ARGO-1127 Wrap offsets low level methods into one

---

argo-ams-library.spec

Reverts ARGOeu/argo-ams-library#68

Revert " Spec update"

---

Jenkinsfile

Add jenkisfile to run on pipeline with test step and package step for centos6 and centos7

DEVOPS-96 Add jenkinsfile for ams-lib

---

Jenkinsfile
Pipfile

Upload to python package index automatically when we cut a new version of ams-library

DEVOPS-109 Update jenkins file for argo-ams-library to upload to pip

---

CHANGELOG.md
examples/retry.py
pymod/ams.py
pymod/amssubscription.py
tests/test_errorclient.py
tests/test_subscription.py

ARGO-2479 Modify subscription offset method fails

---

argo-ams-library.spec
pymod/ams.py

- ARGO-2479 Modify subscription offset method fails
- ARGO-2360 Fix ack_sub retry loop

Version bump

---

CHANGELOG.md
argo-ams-library.spec
setup.py

ARGO-2592 ams-library py2 RPM also packages py3 specific modules

Version 0.5.4

---

.gitignore
CHANGELOG.md
argo-ams-library.spec
pymod/ams.py
setup.py
tests/amsmocks.py
tests/test_authenticate.py

**Added** 
- ARGO-2768 ams-library: support for AMS authorization header

Version 0.5.5

---

pymod/amsmsg.py

Add support for recent python versions

---

pymod/ams.py
tests/test_metrics.py

GET Get Operational Metrics
GET Get Health status
GET Get Daily Message Average
GET version
Also, add support to the internal http functionality to handle url query paramas.

AM-227 ams-library: add support for miscellaneous api calls

---

pymod/ams.py
tests/test_metrics.py
tests/test_project.py

This PR adds functionality that supports the following api calls:
- CRUD for projects (/v1/projects/{name})
- user usage report (/v1/users/usageReport)

AM-225 AMS Library Support for more API Calls
